"""Canonical environment variable names used by configuration loading."""

from __future__ import annotations

ENV_APP_CONFIG_FILE = "APP_CONFIG_FILE"
ENV_PICO_VOICE_ACCESS_KEY = "PICO_VOICE_ACCESS_KEY"
ENV_HF_TOKEN = "HF_TOKEN"
ENV_ORACLE_GOOGLE_CALENDAR_ID = "ORACLE_GOOGLE_CALENDAR_ID"
ENV_ORACLE_GOOGLE_SERVICE_ACCOUNT_FILE = "ORACLE_GOOGLE_SERVICE_ACCOUNT_FILE"
ENV_LLM_SYSTEM_PROMPT = "LLM_SYSTEM_PROMPT"
